export const SET_CURRENT_INGREDIENT_ID = 'SET_CURRENT_INGREDIENT_ID';
export const REMOVE_CURRENT_INGREDIENT_ID = 'REMOVE_CURRENT_INGREDIENT_ID';

export const SET_CURRENT_ORDER_NUMBER = 'SET_CURRENT_ORDER_NUMBER';
export const REMOVE_CURRENT_ORDER_NUMBER = 'REMOVE_CURRENT_ORDER_NUMBER';
